MAX_CLIENTS = 8
PKT_STATS_BUF_SIZE = 30

OUTPUT_DIR = "./scan_results"
RES_FILE_EXT = ".csv"

#direct copy of topics.h
#TOPICS

TOPIC_CMD_BASE = "cmd"
TOPIC_CMD_ALL = f"{TOPIC_CMD_BASE}/all"
TOPIC_DATA_BASE = "data"

CMD_SCAN = "scan"
CMD_STOP = "stop"
CMD_CRASH = "crash"
CMD_SELECT_AP = "select_ap"
CMD_REGISTER = "register"

CMD_ALL_STOP = f"{TOPIC_CMD_ALL}/{CMD_STOP}"
CMD_ALL_SELECT = f"{TOPIC_CMD_ALL}/select"

SCANNER_SUB_CMD_ALL = f"{TOPIC_CMD_ALL}/+"
SCANNER_SUB_CMD_ID = f"{TOPIC_CMD_BASE}/+/+"

MANAGER_SUB_CMD_ID = f"{TOPIC_CMD_BASE}/+/+"

SCANNER_PUB_CMD_REGISTER = f"{TOPIC_CMD_BASE}/{CMD_REGISTER}"  # + id
SCANNER_PUB_CMD_STOP = f"{TOPIC_CMD_BASE}/{CMD_STOP}"          # + id
SCANNER_PUB_CMD_CRASH = f"{TOPIC_CMD_BASE}/{CMD_CRASH}"        # + id

SCANNER_PUB_DATA = TOPIC_DATA_BASE  # + id

MANAGER_SUB_DATA = f"{TOPIC_DATA_BASE}/+"

MANAGER_SUB_CMD_REGISTER = f"{SCANNER_PUB_CMD_REGISTER}/+"
MANAGER_SUB_CMD_STOP = f"{SCANNER_PUB_CMD_STOP}/+"  # use the same register to unregister
MANAGER_SUB_CMD_CRASH = f"{SCANNER_PUB_CMD_CRASH}/+"

MANAGER_PUB_CMD_SCAN = f"{TOPIC_CMD_ALL}/{CMD_SCAN}"
MANAGER_PUB_CMD_STOP = f"{TOPIC_CMD_ALL}/{CMD_STOP}"
MANAGER_PUB_CMD_SELECT_AP = f"{TOPIC_CMD_ALL}/{CMD_SELECT_AP}"

SCANNER_REG_ACK = "reg_ack"
SCANNER_PING_REQ = "ping"
SCANNER_PING_RESP = "pong"


# Scanner
SCAN_CRASH_WAIT = 60

# Graph

X_AXIS_SPAN = 100