#ifndef TOPICS_H
#define TOPICS_H

#define TOPIC_CMD_BASE "cmd"
#define TOPIC_CMD_ALL TOPIC_CMD_BASE "/all"
#define TOPIC_DATA_BASE "data"

#define CMD_SCAN "scan"
#define CMD_STOP "stop"
#define CMD_CRASH "crash"
#define CMD_SELECT_AP "select_ap"
#define CMD_REGISTER "register"
#define CMD_READY "ready"
#define CMD_END "end"

#define CMD_ALL_STOP TOPIC_CMD_ALL "/" CMD_STOP
#define CMD_ALL_SELECT TOPIC_CMD_ALL "/select"

#define SCANNER_SUB_CMD_ALL TOPIC_CMD_ALL "/+"
#define SCANNER_SUB_CMD_ID TOPIC_CMD_BASE "/+/+"

#define SCANNER_PUB_CMD_READY TOPIC_CMD_BASE "/" CMD_READY       // + id
#define SCANNER_PUB_CMD_REGISTER TOPIC_CMD_BASE "/" CMD_REGISTER // + id
#define SCANNER_PUB_CMD_STOP TOPIC_CMD_BASE "/" CMD_STOP         // + id
#define SCANNER_PUB_CMD_CRASH TOPIC_CMD_BASE "/" CMD_CRASH       // + id

#define SCANNER_PUB_DATA TOPIC_DATA_BASE // + id

#define MANAGER_SUB_DATA TOPIC_DATA_BASE "/+"

#define MANAGER_SUB_CMD_REGISTER SCANNER_PUB_CMD_REGISTER "/+"
#define MANAGER_SUB_CMD_STOP SCANNER_PUB_CMD_STOP "/+" // use the same register to unregister
#define MANAGER_SUB_CMD_CRASH SCANNER_PUB_CMD_CRASH "/+"
#define MANAGER_PUB_CMD_SCAN TOPIC_CMD_ALL "/" CMD_SCAN
#define MANAGER_PUB_CMD_STOP TOPIC_CMD_ALL "/" CMD_STOP
#define MANAGER_PUB_CMD_SELECT_AP TOPIC_CMD_ALL "/" CMD_SELECT_AP

// #define MANAGER_PUB_CMD_SELECT TOPIC_CMD_ALL CMD_SELECT

#define SCANNER_REG_ACK "reg_ack"

#define SCANNER_PING_REQ "ping"

#define SCANNER_PING_RESP "pong"

#endif