#ifndef TOPICS_H
#define TOPICS_H

#define TOPIC_CMD_BASE "cmd"
#define TOPIC_CMD_ALL TOPIC_CMD_BASE"/all"
#define TOPIC_DATA_BASE "data"

#define CMD_ALL_STOP TOPIC_CMD_ALL"/stop"
#define CMD_SELECT TOPIC_CMD_ALL"/select"

#define DATA_PKT "/pkt"
#define DATA_APLIST "/aplist"

#define SCANNER_SUB_CMD_ALL TOPIC_CMD_ALL"/+"
#define SCANNER_SUB_CMD_ID TOPIC_CMD_BASE"/+/+"

#define SCANNER_PUB_CMD_REGISTER TOPIC_CMD_BASE"/register"// + id
#define SCANNER_PUB_CMD_STOP TOPIC_CMD_BASE"/stop"// + id

#define SCANNER_PUB_DATA_PKT TOPIC_DATA_BASE DATA_PKT // + id
#define SCANNER_PUB_DATA_APLIST TOPIC_DATA_BASE DATA_APLIST // + id

#define MANAGER_SUB_DATA_PKT TOPIC_DATA_BASE"/+"DATA_PKT
#define MANAGER_SUB_DATA_AP_LIST TOPIC_DATA_BASE"/+"DATA_APLIST
#define MANAGER_SUB_CMD_REGISTER SCANNER_PUB_CMD_REGISTER"/+"
#define MANAGER_SUB_CMD_STOP SCANNER_PUB_CMD_STOP"/+"

#define MANAGER_PUB_CMD_SELECT TOPIC_CMD_ALL CMD_SELECT

#define SCANNER_REG_ACK "reg_ack"

#define SCANNER_PING_REQ "ping"

#define SCANNER_PING_RESP "pong"

#endif